/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_fenced_code_block_token1 = 1,
  sym_paragraph_break = 2,
  sym_newline = 3,
  sym_text_content = 4,
  sym_list_item = 5,
  sym_any_char = 6,
  sym_document = 7,
  sym__item = 8,
  sym_paragraph = 9,
  sym_list = 10,
  sym_fenced_code_block = 11,
  sym_text_line = 12,
  aux_sym_document_repeat1 = 13,
  aux_sym_paragraph_repeat1 = 14,
  aux_sym_list_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_fenced_code_block_token1] = "fenced_code_block_token1",
  [sym_paragraph_break] = "paragraph_break",
  [sym_newline] = "newline",
  [sym_text_content] = "text_content",
  [sym_list_item] = "list_item",
  [sym_any_char] = "any_char",
  [sym_document] = "document",
  [sym__item] = "_item",
  [sym_paragraph] = "paragraph",
  [sym_list] = "list",
  [sym_fenced_code_block] = "fenced_code_block",
  [sym_text_line] = "text_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_fenced_code_block_token1] = aux_sym_fenced_code_block_token1,
  [sym_paragraph_break] = sym_paragraph_break,
  [sym_newline] = sym_newline,
  [sym_text_content] = sym_text_content,
  [sym_list_item] = sym_list_item,
  [sym_any_char] = sym_any_char,
  [sym_document] = sym_document,
  [sym__item] = sym__item,
  [sym_paragraph] = sym_paragraph,
  [sym_list] = sym_list,
  [sym_fenced_code_block] = sym_fenced_code_block,
  [sym_text_line] = sym_text_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_fenced_code_block_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_paragraph_break] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [sym_list_item] = {
    .visible = true,
    .named = true,
  },
  [sym_any_char] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_fenced_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\r') ADVANCE(25);
      if (lookahead == '`') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead == '*' ||
          lookahead == '-') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '`') ADVANCE(10);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '`') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '`') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      if (lookahead == '*' ||
          lookahead == '-') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(2);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token1);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_paragraph_break);
      if (lookahead == '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '.') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '`') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead == '*' ||
          lookahead == '-') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '`') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(5);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '`') ADVANCE(17);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(5);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '`') ADVANCE(19);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(5);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_list_item);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_list_item);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_any_char);
      if (lookahead == '\n') ADVANCE(13);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_any_char);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(2);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_any_char);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_fenced_code_block_token1] = ACTIONS(1),
    [sym_paragraph_break] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_text_content] = ACTIONS(1),
    [sym_list_item] = ACTIONS(1),
    [sym_any_char] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(15),
    [sym__item] = STATE(2),
    [sym_paragraph] = STATE(2),
    [sym_list] = STATE(2),
    [sym_fenced_code_block] = STATE(2),
    [sym_text_line] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_fenced_code_block_token1] = ACTIONS(5),
    [sym_paragraph_break] = ACTIONS(7),
    [sym_newline] = ACTIONS(9),
    [sym_text_content] = ACTIONS(11),
    [sym_list_item] = ACTIONS(13),
    [sym_any_char] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym_list] = STATE(3),
    [sym_fenced_code_block] = STATE(3),
    [sym_text_line] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(15),
    [aux_sym_fenced_code_block_token1] = ACTIONS(5),
    [sym_paragraph_break] = ACTIONS(17),
    [sym_newline] = ACTIONS(9),
    [sym_text_content] = ACTIONS(11),
    [sym_list_item] = ACTIONS(13),
    [sym_any_char] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym__item] = STATE(3),
    [sym_paragraph] = STATE(3),
    [sym_list] = STATE(3),
    [sym_fenced_code_block] = STATE(3),
    [sym_text_line] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_paragraph_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(19),
    [aux_sym_fenced_code_block_token1] = ACTIONS(21),
    [sym_paragraph_break] = ACTIONS(24),
    [sym_newline] = ACTIONS(27),
    [sym_text_content] = ACTIONS(30),
    [sym_list_item] = ACTIONS(33),
    [sym_any_char] = ACTIONS(24),
  },
  [STATE(4)] = {
    [sym_text_line] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(36),
    [aux_sym_fenced_code_block_token1] = ACTIONS(38),
    [sym_paragraph_break] = ACTIONS(40),
    [sym_newline] = ACTIONS(42),
    [sym_text_content] = ACTIONS(11),
    [sym_list_item] = ACTIONS(38),
    [sym_any_char] = ACTIONS(38),
  },
  [STATE(5)] = {
    [sym_text_line] = STATE(5),
    [aux_sym_paragraph_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(44),
    [aux_sym_fenced_code_block_token1] = ACTIONS(46),
    [sym_paragraph_break] = ACTIONS(46),
    [sym_newline] = ACTIONS(48),
    [sym_text_content] = ACTIONS(51),
    [sym_list_item] = ACTIONS(46),
    [sym_any_char] = ACTIONS(46),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_list_repeat1,
    ACTIONS(58), 2,
      sym_paragraph_break,
      sym_newline,
    ACTIONS(56), 4,
      aux_sym_fenced_code_block_token1,
      sym_text_content,
      sym_list_item,
      sym_any_char,
  [17] = 3,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      aux_sym_list_repeat1,
    ACTIONS(62), 6,
      aux_sym_fenced_code_block_token1,
      sym_paragraph_break,
      sym_newline,
      sym_text_content,
      sym_list_item,
      sym_any_char,
  [32] = 4,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      aux_sym_list_repeat1,
    ACTIONS(68), 2,
      sym_paragraph_break,
      sym_newline,
    ACTIONS(66), 4,
      aux_sym_fenced_code_block_token1,
      sym_text_content,
      sym_list_item,
      sym_any_char,
  [49] = 3,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 2,
      sym_paragraph_break,
      sym_newline,
    ACTIONS(73), 4,
      aux_sym_fenced_code_block_token1,
      sym_text_content,
      sym_list_item,
      sym_any_char,
  [63] = 2,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 6,
      aux_sym_fenced_code_block_token1,
      sym_paragraph_break,
      sym_newline,
      sym_text_content,
      sym_list_item,
      sym_any_char,
  [75] = 2,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 6,
      aux_sym_fenced_code_block_token1,
      sym_paragraph_break,
      sym_newline,
      sym_text_content,
      sym_list_item,
      sym_any_char,
  [87] = 2,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 6,
      aux_sym_fenced_code_block_token1,
      sym_paragraph_break,
      sym_newline,
      sym_text_content,
      sym_list_item,
      sym_any_char,
  [99] = 2,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 6,
      aux_sym_fenced_code_block_token1,
      sym_paragraph_break,
      sym_newline,
      sym_text_content,
      sym_list_item,
      sym_any_char,
  [111] = 2,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 6,
      aux_sym_fenced_code_block_token1,
      sym_paragraph_break,
      sym_newline,
      sym_text_content,
      sym_list_item,
      sym_any_char,
  [123] = 1,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
  [127] = 1,
    ACTIONS(91), 1,
      sym_list_item,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 17,
  [SMALL_STATE(8)] = 32,
  [SMALL_STATE(9)] = 49,
  [SMALL_STATE(10)] = 63,
  [SMALL_STATE(11)] = 75,
  [SMALL_STATE(12)] = 87,
  [SMALL_STATE(13)] = 99,
  [SMALL_STATE(14)] = 111,
  [SMALL_STATE(15)] = 123,
  [SMALL_STATE(16)] = 127,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_line, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_line, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_plain(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "plain",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
